const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const offices=[
{name:"مدار للاستشارات الهندسية",cities:["الرياض"],types:["villa","duplex","building","rest","addition","renovation"],max:1500,base:18500,extra:28,arch:.62,days:26,rev:3,score:96,boq:2500,pool:1500,basement:4000,elevator:1800,supervision:6500,urgent:.18},
{name:"أبعاد الهندسية",cities:["الرياض","جدة"],types:["villa","duplex","building","rest","addition"],max:2200,base:21000,extra:31,arch:.6,days:21,rev:4,score:93,boq:2900,pool:1700,basement:4500,elevator:2100,supervision:7200,urgent:.2},
{name:"رؤية للاستشارات",cities:["الرياض","الخبر","الدمام"],types:["villa","duplex","rest","addition","renovation"],max:1200,base:17000,extra:26,arch:.65,days:30,rev:2,score:89,boq:2200,pool:1400,basement:3800,elevator:1700,supervision:5800,urgent:.15},
{name:"مسار الهندسية",cities:["جدة","الخبر","الدمام"],types:["villa","duplex","building"],max:3000,base:23500,extra:33,arch:.58,days:24,rev:5,score:91,boq:3200,pool:1800,basement:4800,elevator:2200,supervision:7500,urgent:.18}
];
function d(){return{type:$("#type").value,city:$("#city").value,land:+$("#land").value,built:+$("#built").value,floors:$("#floors").value,pkg:$("#package").value,pool:$("#pool").checked,basement:$("#basement").checked,elevator:$("#elevator").checked,urgent:$("#urgent").checked}}
function price(p,x){let v=p.base+Math.max(0,x.built-500)*p.extra;if(x.pkg==="arch")v*=p.arch;if(x.pkg==="fullboq")v+=p.boq;if(x.pkg==="supervision")v+=p.supervision;if(x.pool)v+=p.pool;if(x.basement)v+=p.basement;if(x.elevator)v+=p.elevator;if(x.type==="addition")v+=4200;if(x.type==="renovation")v+=3000;if(x.type==="building")v*=1.18;if(x.urgent)v*=1+p.urgent;return Math.round(v)}
const money=n=>new Intl.NumberFormat("ar-SA").format(n);
$("#form").onsubmit=e=>{e.preventDefault();render()};
$("#edit").onclick=()=>{$("#form").scrollIntoView({behavior:"smooth"})};
function render(){let x=d(),ps=offices.filter(p=>p.cities.includes(x.city)&&p.types.includes(x.type)&&x.built<=p.max);$("#results").classList.remove("hidden");$("#resultHeading").textContent=ps.length+" عروض هندسية مناسبة";$("#summary").innerHTML="<b>"+labelType(x.type)+" • "+x.city+"</b> — أرض "+x.land+"م² • بناء "+x.built+"م² • "+labelPkg(x.pkg)+(x.pool?" • مسبح":"")+(x.basement?" • بدروم":"")+(x.elevator?" • مصعد":"")+(x.urgent?" • أولوية عاجلة":"");$("#cards").innerHTML=ps.length?ps.map((p,i)=>card(p,x,i)).join(""):'<div class="card"><b>لا توجد مطابقة تلقائية في بيانات الديمو</b><p>في المنتج الحقيقي يمكن تحويل الحالة لطلب مراجعة من مكاتب إضافية.</p></div>';$("#compare").innerHTML=ps.length>1?'<div class="compare"><h3>قارن بنفس البنود</h3><table><tr><th>البند</th>'+ps.map(p=>"<th>"+p.name+"</th>").join("")+'</tr><tr><td>السعر التجريبي</td>'+ps.map(p=>"<td><b>"+money(price(p,x))+" ر.س*</b></td>").join("")+'</tr><tr><td>المدة*</td>'+ps.map(p=>"<td>"+p.days+" يوم عمل</td>").join("")+'</tr><tr><td>جولات التعديل*</td>'+ps.map(p=>"<td>"+p.rev+"</td>").join("")+'</tr><tr><td>نطاق الخدمة</td>'+ps.map(p=>"<td>"+labelPkg(x.pkg)+"</td>").join("")+'</tr><tr><td>درجة المطابقة</td>'+ps.map(p=>"<td>"+p.score+"%</td>").join("")+'</tr></table></div>':"";$("#results").scrollIntoView({behavior:"smooth"})}
function card(p,x,i){let v=price(p,x);return '<article class="card '+(i===0?"best":"")+'">'+(i===0?'<span class="besttag">أعلى مطابقة</span>':'')+'<div class="cardhead"><span class="avatar">'+p.name[0]+'</span><div><b>'+p.name+'*</b><small>'+x.city+' • مكتب افتراضي</small></div><span class="score">'+p.score+'%</span></div><div class="price">'+money(v)+' ر.س*</div><div class="price-note">سعر تجريبي حسب البيانات المدخلة</div><ul><li>'+labelPkg(x.pkg)+'</li><li>مدة مستهدفة*: '+p.days+' يوم عمل</li><li>تعديلات*: '+p.rev+' جولات</li><li>المشروع ضمن حدود قبول المكتب ✓</li></ul><button onclick="details(\''+p.name+'\')">تفاصيل العرض</button><button class="cta" onclick="choose(\''+p.name+'\')">اختيار / طلب تواصل</button></article>'}
function labelType(v){return{villa:"فيلا جديدة",building:"عمارة سكنية صغيرة",duplex:"دوبلكس",rest:"استراحة",addition:"إضافة دور / ملحق",renovation:"تعديل/ترميم"}[v]}
function labelPkg(v){return{full:"تصميم متكامل (معماري + إنشائي + MEP)",arch:"تصميم معماري فقط",fullboq:"تصميم متكامل + BOQ",supervision:"تصميم متكامل + إشراف"}[v]}
window.details=name=>{let p=offices.find(o=>o.name===name),x=d(),v=price(p,x);open('<span>عرض هندسي تجريبي</span><h2>'+p.name+'</h2><p>'+labelType(x.type)+' • '+x.city+' • '+x.built+'م² بناء</p><div class="detailrows"><div><span>نطاق الخدمة</span><b>'+labelPkg(x.pkg)+'</b></div><div><span>السعر المحسوب*</span><b>'+money(v)+' ر.س</b></div><div><span>المدة المستهدفة*</span><b>'+p.days+' يوم عمل</b></div><div><span>جولات التعديل*</span><b>'+p.rev+'</b></div><div><span>صلاحية العرض التجريبي</span><b>7 أيام*</b></div></div><h3>يشمل في هذا المثال</h3><ul><li>جلسة فهم المتطلبات والبرنامج المعماري</li><li>المخرجات المحددة حسب الباقة المختارة</li><li>تنسيق التخصصات المشمولة</li><li>عدد التعديلات الموضح أعلاه</li></ul><div class="notice">كل الأرقام والشروط هنا افتراضية. في المنتج الفعلي يضبط كل مكتب قواعده وشروط عرضه قبل ظهوره للعميل.</div><button class="cta" style="width:100%" onclick="choose(\''+p.name+'\')">اختيار هذا المكتب</button>')}
window.choose=name=>open('<span>الخطوة التالية — بسيطة</span><h2>اخترت '+name+'*</h2><p>في نطاق الـMVP نقف هنا تقريباً: نحفظ بيانات العميل والمشروع، ونرسل طلب التواصل/تأكيد العرض للمكتب.</p><div class="detailrows"><div><span>1</span><b>تأكيد رقم الجوال</b></div><div><span>2</span><b>مشاركة نطاق المشروع مع المكتب</b></div><div><span>3</span><b>المكتب يؤكد العرض أو يطلب معلومة ناقصة</b></div></div><div class="notice">لا ندخل حالياً في المقاولين، التنفيذ، إدارة المشروع أو دفعات البناء. التركيز هو سرعة الحصول على عروض هندسية قابلة للمقارنة.</div><button class="cta" style="width:100%">إرسال طلب تجريبي</button>');
function open(h){$("#modalbody").innerHTML=h;$("#modal").classList.remove("hidden")}$("#close").onclick=()=>$("#modal").classList.add("hidden");$("#modal").onclick=e=>{if(e.target===$("#modal"))$("#modal").classList.add("hidden")};
const examples={villa:{type:"villa",city:"الرياض",land:450,built:650,pkg:"fullboq"},smallvilla:{type:"villa",city:"الرياض",land:300,built:420,pkg:"full"},luxury:{type:"villa",city:"الرياض",land:750,built:1050,pkg:"fullboq",pool:1,elevator:1},duplex:{type:"duplex",city:"جدة",land:500,built:720,pkg:"full"},building:{type:"building",city:"الرياض",land:600,built:1400,pkg:"fullboq"},addition:{type:"addition",city:"الرياض",land:450,built:300,pkg:"full"},arch:{type:"villa",city:"الرياض",land:400,built:550,pkg:"arch"},urgent:{type:"villa",city:"الرياض",land:400,built:600,pkg:"full",urgent:1},basement:{type:"villa",city:"الرياض",land:600,built:900,pkg:"fullboq",basement:1,elevator:1}};
$$("[data-example]").forEach(b=>b.onclick=()=>{let x=examples[b.dataset.example];$("#type").value=x.type;$("#city").value=x.city;$("#land").value=x.land;$("#built").value=x.built;$("#package").value=x.pkg;["pool","basement","elevator","urgent"].forEach(k=>$("#"+k).checked=!!x[k]);location.hash="quote";setTimeout(render,250)});