const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];$("#menu").onclick=()=>$("#nav").classList.toggle("open");$$("#nav a").forEach(a=>a.onclick=()=>$("#nav").classList.remove("open"));
const providers=[
{name:"مدار للاستشارات",contractor:"أساس البناء",cities:["الرياض"],max:1500,engBase:18500,extra:28,mult:1,build:1580,days:26,revisions:3,score:96},
{name:"أبعاد الهندسية",contractor:"ركائز للمقاولات",cities:["الرياض","جدة"],max:2200,engBase:21000,extra:31,mult:1.06,build:1660,days:21,revisions:4,score:93},
{name:"بنيان للاستشارات",contractor:"إتقان للمقاولات",cities:["الرياض","الخبر","الدمام"],max:1200,engBase:17000,extra:26,mult:.97,build:1510,days:31,revisions:2,score:89},
{name:"رؤية العمران",contractor:"صرح التنفيذ",cities:["جدة","الخبر","الدمام"],max:3000,engBase:24000,extra:34,mult:1.1,build:1720,days:24,revisions:5,score:91}
];
const scenarioInfo={villa:["فيلا جديدة","تصميم متكامل + تنفيذ اختياري"],turnkey:["تسليم مفتاح","من التصميم حتى الاستلام"],design:["تصميم وترخيص","خدمات هندسية فقط"],execute:["تنفيذ فقط","مخططات + BOQ → مقاول"],renovation:["ترميم","تقييم قائم → نطاق ترميم"],floor:["إضافة دور/ملحق","فحص إنشائي → تصميم → تنفيذ"],building:["عمارة سكنية","نطاق متعدد الوحدات"]};
function data(){return{scenario:$("#scenario").value,city:$("#city").value,land:+$("#land").value||0,built:+$("#built").value||0,finish:$("#finish").value,floors:+$("#floors").value,drawings:$("#drawings").value,pool:$("#pool").checked,basement:$("#basement").checked,elevator:$("#elevator").checked,boq:$("#boq").checked,supervision:$("#supervision").checked,urgent:$("#urgent").checked,deed:$("#deed").checked,survey:$("#survey").checked,soil:$("#soil").checked,photos:$("#photos").checked}}
function scope(){const d=data(),info=scenarioInfo[d.scenario];$("#scenarioBadge").textContent=info[0];let stages=[];if(!["execute","renovation"].includes(d.scenario))stages.push("تصميم معماري","تصميم إنشائي","MEP");if(d.boq)stages.push("جدول كميات BOQ");if(d.supervision)stages.push("إشراف هندسي");if(["villa","turnkey","execute","renovation","floor","building"].includes(d.scenario))stages.push(d.scenario==="renovation"?"أعمال الترميم":"تنفيذ الأعمال");if(d.scenario==="floor")stages.unshift("تقييم/فحص القائم");let docs=[d.deed?"بيانات الملكية ✓":"بيانات الملكية ناقصة",d.survey?"المساحي ✓":"المساحي غير متوفر",d.drawings==="ready"?"المخططات + BOQ جاهزة ✓":"المخططات النهائية غير جاهزة"];$("#scopeOut").innerHTML='<div class="scope-list"><div class="scope-item"><span>المسار</span><b>'+info[1]+'</b></div><div class="scope-item"><span>الموقع والحجم</span><b>'+d.city+' • '+d.built.toLocaleString("ar-SA")+'م²</b></div><div class="scope-item"><span>المخرجات</span><b>'+stages.join(" • ")+'</b></div><div class="scope-item"><span>جاهزية البيانات</span><b>'+docs.join(" • ")+'</b></div></div>'}
$$("input,select").forEach(x=>x.addEventListener("change",scope));scope();
function calc(p,d){let eng=p.engBase+Math.max(0,d.built-500)*p.extra;if(d.pool)eng+=1500;if(d.basement)eng+=4000;if(d.elevator)eng+=1800;if(d.boq)eng+=2500;if(d.supervision)eng+=6500;if(d.scenario==="floor")eng+=4500;if(d.scenario==="building")eng*=1.35;if(d.urgent)eng*=1.18;eng*=p.mult;let rate=p.build*(d.finish==="economy"?.84:d.finish==="premium"?1.38:1);let build=d.built*rate;if(d.pool)build+=65000;if(d.basement)build+=d.built*.22*rate;if(d.elevator)build+=90000;if(d.scenario==="renovation")build=d.built*rate*.48;if(d.scenario==="floor")build=d.built*rate*.62;if(d.floors>=4)build*=1.08;let type=d.scenario==="design"?"eng":d.scenario==="execute"?"build":"both";return{eng:Math.round(eng),build:Math.round(build),total:Math.round(type==="eng"?eng:type==="build"?build:eng+build),type}}
function money(n){return new Intl.NumberFormat("ar-SA",{maximumFractionDigits:0}).format(n)}
$("#projectForm").onsubmit=e=>{e.preventDefault();renderOffers();$("#results").classList.remove("hidden");$("#results").scrollIntoView({behavior:"smooth"})};
function renderOffers(){const d=data();let eligible=providers.filter(p=>p.cities.includes(d.city)&&d.built<=p.max);if(d.scenario==="building")eligible=eligible.filter(p=>p.max>=1800||d.built<1800);$("#matchCount").textContent=eligible.length;const cards=$("#offerCards");cards.innerHTML="";if(!eligible.length){cards.innerHTML='<div class="panel">لا توجد مطابقة تلقائية لهذا الحجم/المدينة في بيانات العرض التجريبية. في المنتج الفعلي ينتقل الطلب لمسار تسعير يدوي.</div>';$("#compareWrap").innerHTML="";return}let rows=[];eligible.forEach((p,i)=>{const c=calc(p,d),finalReady=d.drawings==="ready"||c.type==="eng",label=c.type==="eng"?"عرض هندسي شبه فوري":finalReady?"عرض تنفيذ قابل للتأكيد":"تقدير تنفيذ أولي";let art=document.createElement("article");art.className="offer "+(i===0?"best":"");art.innerHTML=(i===0?'<span class="tag">أفضل تطابق مع المدخلات</span>':'')+'<span class="score">'+p.score+'%</span><h3>'+p.name+'</h3><div class="sub">'+(c.type!=="eng"?"مع "+p.contractor+" • ":"")+label+'</div><div class="price">'+money(c.total)+' <small>ر.س*</small></div><ul><li>هندسي: '+money(c.eng)+' ر.س</li>'+(c.type!=="eng"?'<li>تنفيذ تقديري: '+money(c.build)+' ر.س</li>':'')+'<li>مدة التصميم: '+p.days+' يوم عمل</li><li>تعديلات التصميم: '+p.revisions+'</li><li>نطاق موحد للمقارنة ✓</li></ul><button class="detail">فتح عرض السعر</button><button class="primary contract">اختيار ومتابعة التعاقد</button>';art.querySelector(".detail").onclick=()=>openQuote(p,c,d,false);art.querySelector(".contract").onclick=()=>openQuote(p,c,d,true);cards.appendChild(art);rows.push({p,c})});$("#compareWrap").innerHTML='<div class="compare"><h3>مقارنة Apple-to-Apple</h3><table><tr><th>البند</th>'+rows.map(x=>'<th>'+x.p.name+'</th>').join("")+'</tr><tr><td>درجة المطابقة</td>'+rows.map(x=>'<td>'+x.p.score+'%</td>').join("")+'</tr><tr><td>الخدمات الهندسية</td>'+rows.map(x=>'<td>'+money(x.c.eng)+' ر.س</td>').join("")+'</tr><tr><td>التنفيذ</td>'+rows.map(x=>'<td>'+(x.c.type==="eng"?"—":money(x.c.build)+" ر.س*")+'</td>').join("")+'</tr><tr><td>مدة التصميم</td>'+rows.map(x=>'<td>'+x.p.days+' يوم</td>').join("")+'</tr><tr><td>التعديلات</td>'+rows.map(x=>'<td>'+x.p.revisions+'</td>').join("")+'</tr><tr><td>BOQ</td>'+rows.map(x=>'<td>'+(d.boq?"مشمول":"غير مختار")+'</td>').join("")+'</tr><tr><td>إشراف</td>'+rows.map(x=>'<td>'+(d.supervision?"مشمول":"غير مختار")+'</td>').join("")+'</tr></table><small>*جميع القيم تجريبية. تقدير التنفيذ ليس سعراً نهائياً قبل اكتمال نطاق التنفيذ.</small></div>'}
function openQuote(p,c,d,contract){let readiness=d.drawings==="ready"?"المخططات وBOQ متوفرة — جاهزية أعلى للتسعير النهائي":"السعر التنفيذي تقديري حتى اكتمال واعتماد المخططات وBOQ";$("#modalContent").innerHTML='<div class="quote-detail"><span class="eyebrow">QUOTATION • DEMO Q-260918-'+Math.floor(100+Math.random()*899)+'</span><h2>عرض مشروع '+scenarioInfo[d.scenario][0]+'</h2><p>'+p.name+(c.type!=="eng"?" + "+p.contractor:"")+'</p><div class="quote-summary"><div><small>القيمة المعروضة</small><b>'+money(c.total)+' ر.س*</b></div><div><small>مدة التصميم</small><b>'+p.days+' يوم</b></div><div><small>صلاحية النموذج</small><b>7 أيام</b></div></div><h3>نطاق العرض</h3><ul><li>تجميع متطلبات العميل وتحويلها إلى Scope موحد.</li><li>التصميم المعماري والإنشائي وMEP حسب المسار المختار.</li><li>'+(d.boq?"إعداد/استخدام جدول كميات ضمن النطاق.":"BOQ غير مختار في هذا السيناريو.")+'</li><li>'+(d.supervision?"الإشراف الهندسي ضمن الخيارات.":"الإشراف غير مشمول حالياً.")+'</li><li>'+readiness+'</li></ul><h3>تفصيل القيمة</h3><table><tr><td>الخدمات الهندسية</td><th>'+money(c.eng)+' ر.س</th></tr>'+(c.type!=="eng"?'<tr><td>التنفيذ '+(d.drawings==="ready"?"(قابل للتأكيد بعد مراجعة الملفات)":"(تقديري)")+'</td><th>'+money(c.build)+' ر.س</th></tr>':'')+'<tr><td>الإجمالي التجريبي</td><th>'+money(c.total)+' ر.س</th></tr></table><div class="notice">لا تشمل هذه المحاكاة رسوماً حكومية أو تأميناً أو ضرائب أو بنوداً غير محددة. جميع الأرقام افتراضية لشرح منطق المنتج.</div>'+(contract?'<h3>الانتقال إلى التعاقد</h3><div class="contract-steps"><div><b>1. مراجعة</b><br>العرض والنطاق</div><div><b>2. عقد</b><br>بنود + مراحل</div><div><b>3. دفعة بدء</b><br>حسب الاتفاق</div><div><b>4. مشروع</b><br>فتح لوحة المتابعة</div></div><button id="acceptDemo" class="primary full">موافقة تجريبية وفتح المشروع</button>':'<button id="goContract" class="primary full">اختيار هذا العرض</button>')+'</div>';$("#modal").classList.remove("hidden");setTimeout(()=>{if($("#goContract"))$("#goContract").onclick=()=>openQuote(p,c,d,true);if($("#acceptDemo"))$("#acceptDemo").onclick=()=>{$("#modal").classList.add("hidden");location.hash="dashboard"}},0)}
$("#closeModal").onclick=()=>$("#modal").classList.add("hidden");$("#modal").onclick=e=>{if(e.target===$("#modal"))$("#modal").classList.add("hidden")};
$$("[data-scenario]").forEach(b=>b.onclick=()=>{$("#scenario").value=b.dataset.scenario;scope();location.hash="customer";setTimeout(()=>$("#scenario").focus(),500)});
$$(".tab").forEach(b=>b.onclick=()=>{$$(".tab").forEach(x=>x.classList.remove("active"));b.classList.add("active");$$(".tabpane").forEach(x=>x.classList.add("hidden"));$("#"+b.dataset.tab).classList.remove("hidden")});