const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],money=n=>new Intl.NumberFormat("ar-SA").format(Math.round(n));
const offices=[
{name:"مدار للاستشارات",types:["villa","duplex","building"],max:1600,base:18500,extra:28,days:26,rev:3,boq:2500,pool:1500,basement:4000,elevator:1800,urgent:.18,pay:"30 / 40 / 30",score:96},
{name:"أبعاد الهندسية",types:["villa","duplex","building","addition"],max:2400,base:21000,extra:31,days:21,rev:4,boq:2900,pool:1700,basement:4500,elevator:2100,urgent:.20,pay:"25 / 50 / 25",score:94},
{name:"رؤية العمران",types:["villa","duplex","addition"],max:1200,base:17000,extra:26,days:30,rev:2,boq:2200,pool:1400,basement:3800,elevator:1700,urgent:.15,pay:"40 / 30 / 30",score:91},
{name:"مسار الهندسية",types:["villa","building"],max:3000,base:23500,extra:33,days:24,rev:5,boq:3200,pool:1800,basement:4800,elevator:2200,urgent:.18,pay:"30 / 50 / 20",score:90},
{name:"رُكن التصميم",types:["villa","duplex"],max:900,base:16000,extra:30,days:28,rev:3,boq:2400,pool:1600,basement:4200,elevator:1900,urgent:.22,pay:"50 / 25 / 25",score:88},
{name:"أفق للاستشارات",types:["villa","duplex","building"],max:2000,base:19800,extra:29,days:25,rev:3,boq:2700,pool:1550,basement:4100,elevator:1850,urgent:.17,pay:"30 / 30 / 40",score:87},
{name:"خطوط هندسية",types:["villa","addition"],max:1100,base:17500,extra:27,days:32,rev:4,boq:2300,pool:1450,basement:3900,elevator:1750,urgent:.20,pay:"35 / 35 / 30",score:85},
{name:"نواة المعمار",types:["villa","duplex"],max:1400,base:19000,extra:30,days:23,rev:2,boq:2800,pool:1700,basement:4300,elevator:2000,urgent:.19,pay:"30 / 40 / 30",score:84},
{name:"أسس للاستشارات",types:["villa","building","addition"],max:2600,base:22000,extra:32,days:27,rev:3,boq:3000,pool:1750,basement:4600,elevator:2150,urgent:.16,pay:"25 / 50 / 25",score:82},
{name:"مدى الهندسية",types:["villa","duplex","building"],max:1800,base:20500,extra:29,days:29,rev:4,boq:2600,pool:1500,basement:4000,elevator:1800,urgent:.18,pay:"40 / 40 / 20",score:80}];
function service(v){return{full:"مخططات متكاملة",arch:"معماري فقط",boq:"مخططات متكاملة + BOQ"}[v]}function getReq(){return{type:$("#ctype").value,district:$("#district").value,land:+$("#land").value,area:+$("#area").value,service:$("#service").value,floors:+$("#floors").value,pool:$("#pool").checked,basement:$("#basement").checked,elevator:$("#elevator").checked,urgent:$("#urgent").checked,deed:$("#deed").checked,survey:$("#survey").checked,sketch:$("#sketch").checked}}function calc(o,x){let p=o.base+Math.max(0,x.area-500)*o.extra;if(x.service==="arch")p*=.62;if(x.service==="boq")p+=o.boq;if(x.pool)p+=o.pool;if(x.basement)p+=o.basement;if(x.elevator)p+=o.elevator;if(x.floors>=4)p*=1.12;if(x.urgent)p*=1+o.urgent;return p}function eligible(o,x){return o.types.includes(x.type)&&x.area<=o.max}
$$("[data-view]").forEach(b=>b.onclick=()=>{$$("[data-view]").forEach(x=>x.classList.toggle("active",x===b));$$(".screen").forEach(x=>x.classList.remove("active"));$("#"+b.dataset.view).classList.add("active");scrollTo(0,0)});
$("#clientForm").onsubmit=e=>{e.preventDefault();let x=getReq(),ready=x.deed&&x.survey;$("#verification").className="verify "+(ready?"":"warn");$("#verification").innerHTML='<div><b>'+(ready?"✓ الطلب جاهز للمطابقة":"! نحتاج مستنداً إضافياً")+'</b><small>'+(ready?"تمت محاكاة التحقق من البيانات الأساسية. يمكن الآن حساب العروض.":"يمكن عرض أسعار استرشادية، لكن يتحول العرض إلى جاهز للتعاقد بعد استكمال المستندات المطلوبة.")+'</small></div><span>'+(ready?"موثق تجريبياً":"غير مكتمل")+'</span>';renderOffers(x);$("#offersWrap").classList.remove("hidden");$("#verification").scrollIntoView({behavior:"smooth"})};
function renderOffers(x){let list=offices.filter(o=>eligible(o,x)).sort((a,b)=>b.score-a.score).slice(0,6);$("#offerTitle").textContent=list.length+" مكاتب مطابقة من أصل 10*";$("#offers").innerHTML=list.map((o,i)=>'<article class="offer '+(i===0?"best":"")+'">'+(i===0?'<span class="tag">أعلى مطابقة*</span>':'')+'<div class="officehead"><span class="avatar">'+o.name[0]+'</span><div><b>'+o.name+'*</b><small>الرياض • مكتب افتراضي</small></div><span class="score">'+o.score+'%</span></div><div class="price">'+money(calc(o,x))+' ر.س*</div><small>'+service(x.service)+' • محسوب من قواعد المكتب</small><div class="terms"><div><span>مدة مستهدفة*</span><b>'+o.days+' يوم</b></div><div><span>التعديلات*</span><b>'+o.rev+' جولات</b></div><div><span>الدفعات*</span><b>'+o.pay+'%</b></div><div><span>المستندات</span><b>'+(x.deed&&x.survey?"جاهزة":"تحتاج استكمال")+'</b></div></div><button onclick="why('+offices.indexOf(o)+')">كيف حُسب العرض؟</button><button onclick="selectOffer('+offices.indexOf(o)+')">اختيار وبدء التعاقد</button></article>').join("")}
window.why=i=>{let o=offices[i],x=getReq();open('<span>من إعدادات المكتب إلى العرض</span><h2>'+o.name+'*</h2><p>بُنيان لم يخترع السعر؛ طبّق قواعد المكتب على بيانات العميل.</p><div class="contract"><div><span>سعر أساسي حتى 500م²*</span><b>'+money(o.base)+' ر.س</b></div><div><span>المساحة الإضافية*</span><b>'+o.extra+' ر.س/م²</b></div><div><span>مساحة المشروع</span><b>'+x.area+'م²</b></div>'+(x.service==="boq"?'<div><span>BOQ*</span><b>+'+money(o.boq)+' ر.س</b></div>':'')+(x.pool?'<div><span>مسبح*</span><b>+'+money(o.pool)+' ر.س</b></div>':'')+(x.basement?'<div><span>بدروم*</span><b>+'+money(o.basement)+' ر.س</b></div>':'')+(x.elevator?'<div><span>مصعد*</span><b>+'+money(o.elevator)+' ر.س</b></div>':'')+'<div><span>الإجمالي التجريبي</span><b>'+money(calc(o,x))+' ر.س*</b></div></div><div class="note">في المنتج الحقيقي، كل مكتب يعتمد قواعده وحدود التفويض التجاري لبُنيان. الحالات الخارجة عنها تُحال للمكتب للمراجعة قبل التعاقد.</div>')};
window.selectOffer=i=>{let o=offices[i],x=getReq(),ready=x.deed&&x.survey;open('<span>اختيار العميل → بُنيان</span><h2>طلب تعاقد مع '+o.name+'*</h2><p>العميل اختار العرض. ينتقل الآن إلى بُنيان لإغلاق الجانب التجاري نيابةً عن المكتب ضمن حدود التفويض المتفق عليها.</p><div class="contract"><div><span>قيمة العرض*</span><b>'+money(calc(o,x))+' ر.س</b></div><div><span>الخدمة</span><b>'+service(x.service)+'</b></div><div><span>مدة مستهدفة*</span><b>'+o.days+' يوم</b></div><div><span>التعديلات*</span><b>'+o.rev+' جولات</b></div><div><span>الدفعات*</span><b>'+o.pay+'%</b></div><div><span>التحقق</span><b>'+(ready?"مكتمل تجريبياً ✓":"ينقص مستند")+'</b></div></div><div class="actions"><button class="secondary" onclick="showView(\'desk\')">فتح لدى بُنيان</button><button class="primary" '+(ready?"":"disabled")+' onclick="generateContract('+i+')">توليد ملخص التعاقد</button></div>')};
window.generateContract=i=>{let o=offices[i],x=getReq();open('<span>مسودة تعاقد مولدة*</span><h2>ملخص الاتفاق التجاري</h2><p>بين العميل والمكتب الهندسي، بعد اختيار العرض والتحقق من البيانات.</p><div class="contract"><div><span>المكتب*</span><b>'+o.name+'</b></div><div><span>المشروع</span><b>'+x.type+' • '+x.district+' • الرياض</b></div><div><span>النطاق</span><b>'+service(x.service)+'</b></div><div><span>القيمة*</span><b>'+money(calc(o,x))+' ر.س</b></div><div><span>التسليم المستهدف*</span><b>'+o.days+' يوم</b></div><div><span>التعديلات*</span><b>'+o.rev+' جولات</b></div><div><span>الدفعات*</span><b>'+o.pay+'%</b></div></div><div class="note">هذه محاكاة وليست عقداً قانونياً. في التشغيل الفعلي تُراجع صياغة العقد والتفويض والمتطلبات النظامية، ويؤكد المكتب أي حالة تتجاوز قواعده المعتمدة.</div><button class="primary" style="width:100%;margin-top:10px" onclick="handoff('+i+')">محاكاة إتمام التعاقد والتسليم للمكتب</button>')};window.handoff=i=>open('<span>تم الإغلاق التجاري ✓</span><h2>الآن يبدأ العمل الفني مع المكتب</h2><p>تمت محاكاة الاتفاق والتعاقد. تُرسل بيانات العميل والمشروع والمستندات والنطاق المتفق عليه إلى <b>'+offices[i].name+'*</b>.</p><div class="note">هنا تنتهي رحلة بُنيان في V4. التواصل الفني، تطوير التصميم، الاجتماعات والمخرجات تتم مباشرة بين العميل والمكتب الهندسي.</div>');
window.showView=v=>{$("#sheet").classList.add("hidden");document.querySelector('[data-view="'+v+'"]').click()};
$("#officeSelect").innerHTML=offices.map((o,i)=>'<option value="'+i+'">'+(i+1)+'. '+o.name+'*</option>').join("");$("#officeSelect").onchange=renderSettings;function renderSettings(){let o=offices[+$("#officeSelect").value];$("#officeSettings").innerHTML='<div class="settings"><div class="profile"><small>مكتب تجريبي</small><h2>'+o.name+'</h2><p>هذه البيانات هي التي تسمح لبُنيان بالمطابقة والتسعير نيابة عن المكتب.</p><ul><li>النطاق: الرياض فقط</li><li>أنواع المشاريع: '+o.types.join(" • ")+'</li><li>أقصى مساحة: '+money(o.max)+'م²</li><li>حالة استقبال الطلبات: مفعّل*</li></ul></div><div class="settingbox"><h3>قواعد العرض والتعاقد*</h3><div class="settinggrid"><label class="setting">السعر الأساسي<input value="'+money(o.base)+' ر.س"></label><label class="setting">بعد 500م²<input value="'+o.extra+' ر.س / م²"></label><label class="setting">BOQ<input value="'+money(o.boq)+' ر.س"></label><label class="setting">مسبح<input value="'+money(o.pool)+' ر.س"></label><label class="setting">بدروم<input value="'+money(o.basement)+' ر.س"></label><label class="setting">مصعد<input value="'+money(o.elevator)+' ر.س"></label><label class="setting">المدة<input value="'+o.days+' يوم عمل"></label><label class="setting">التعديلات<input value="'+o.rev+' جولات"></label><label class="setting">الدفعات<input value="'+o.pay+'%"></label></div><div class="rules"><b>منطق التفويض التجاري</b><br><code>إذا كان المشروع ضمن الأنواع المقبولة + المساحة ≤ '+o.max+'م² + المستندات المطلوبة مكتملة → بُنيان يستطيع إنشاء العرض حسب القواعد. غير ذلك → مراجعة المكتب.</code></div></div></div>'}renderSettings();
const names=["سارة م.","محمد ع.","خالد ن.","نورة س.","عبدالله ف.","ريم ع.","فيصل م.","هند أ.","تركي س.","لطيفة ر.","سلمان د.","الجوهرة م."];const states=["عروض جاهزة","ينقص مستند","اختار مكتباً","جاهز للتعاقد","عروض جاهزة"];$("#clients").innerHTML=Array.from({length:12},(_,i)=>'<div class="client"><div><b>'+names[i]+'</b><small>REQ-'+(260900+i+31)+' • '+(["فيلا","دوبلكس","فيلا","عمارة"][i%4])+'</small></div><div><b>'+([650,420,900,1400][i%4])+'م²</b><small>مساحة بناء*</small></div><div><b>'+(3+i%5)+' عروض</b><small>مطابقة*</small></div><div><span class="status '+(states[i%5]==="ينقص مستند"?"warn":"")+'">'+states[i%5]+'*</span></div><button onclick="deskCase('+i+')">فتح</button></div>').join("");
window.deskCase=i=>open('<span>حالة تجريبية • Commercial Desk</span><h2>'+names[i]+'</h2><p>طلب '+(["فيلا","دوبلكس","فيلا","عمارة"][i%4])+' في الرياض. الحالة الحالية: <b>'+states[i%5]+'*</b>.</p><div class="contract"><div><span>التحقق من الهوية/التواصل*</span><b>مكتمل</b></div><div><span>بيانات المشروع*</span><b>مكتملة</b></div><div><span>مستندات الملكية*</span><b>'+(i%5===1?"ينقص مستند":"مكتملة")+'</b></div><div><span>العروض المطابقة*</span><b>'+(3+i%5)+'</b></div></div><div class="note">هذه الشاشة تمثل دور بُنيان التشغيلي: استكمال البيانات التجارية، التنسيق، إغلاق الاتفاق، ثم handoff للمكتب. ليست إدارة للعمل الفني.</div>');
function open(h){$("#sheetbody").innerHTML=h;$("#sheet").classList.remove("hidden")}$("#close").onclick=()=>$("#sheet").classList.add("hidden");$("#sheet").onclick=e=>{if(e.target===$("#sheet"))$("#sheet").classList.add("hidden")};